<a href="https://colab.research.google.com/github/DANU011/pytorch/blob/main/mcode/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# gpu 설정 - 수정 > 노트 설정 > 하드웨어 가속기 'GPU'
import torch

In [2]:
# randn()함수 - torch안에서 매트릭스를 만드는데 2, 3 크기로 생성
data = torch.randn(2, 3)
# randn vs rand
# randn : gaussian distribution(정규 분포) 평균 0 분산 1인 분포에서 랜덤하게 sampling 하겠다.
# rand : uniform distribution(연속균등 분포)에서 [0, 1]에서 sampling 하겠다.

In [7]:
data2 = torch.rand(2, 3)

In [3]:
print(data)

tensor([[ 0.6147,  1.5288, -0.9653],
        [-1.0934,  0.9571,  1.1680]])


텐서라는 클래스 안에 데이터 저장

In [4]:
print(data)
print(data * 5)
print(data + data)
print(data.shape)
print(data.dtype)

tensor([[ 0.6147,  1.5288, -0.9653],
        [-1.0934,  0.9571,  1.1680]])
tensor([[ 3.0734,  7.6438, -4.8267],
        [-5.4669,  4.7857,  5.8401]])
tensor([[ 1.2294,  3.0575, -1.9307],
        [-2.1867,  1.9143,  2.3360]])
torch.Size([2, 3])
torch.float32


In [10]:
# 데이터를 생성하는 여러 방법
data = torch.zeros([2, 4])
print(data)
data = torch.ones([2, 4])
print(data)
data = torch.eye(4)
print(data)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [6]:
# list와 차이점 및 벡터 내적 등 수월하게 사용 가능
lst1 = [1, 2]
lst2 = [3, 4]

tor1 = torch.tensor([1, 2])
tor2 = torch.tensor([3, 4])

print(tor1 + tor2)
print(tor1 * tor2)
print(lst1 + lst2) # 단순히 concat. 연산 안됨.
print(lst1 * lst2) # can't multiply sequence by non-int of type 'list'


tensor([4, 6])
tensor([3, 8])
[1, 2, 3, 4]


TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
print(sum(tor1 + tor2)) # [4, 6]의 합
print(tor1.dot(tor2)) # 1 * 3 + 2 * 4 + = 11
print(torch.dot(tor1, tor2))
print(torch.matmul(tor1, tor2))
print(torch.matmul(tor1.view(1, -1), tor2)[0]) # view() shape 맞춰줄 때 사용


tensor(10)
tensor(11)
tensor(11)
tensor(11)
tensor(11)


In [17]:
# 매트릭스의 곱 ( Matrix Multiplication)
mat1 = torch.tensor([[2, 5, 8], [5, 3, 1]]) # shape(2, 3)
mat2 = torch.tensor([[3, 2], [5, 4], [7, 8]]) # shape(3, 2)
print(mat1)
print(mat2)
print(torch.matmul(mat1, mat2)) # matrix 2 * 2
print(torch.matmul(mat2, mat1)) # matrix 3 * 3


tensor([[2, 5, 8],
        [5, 3, 1]])
tensor([[3, 2],
        [5, 4],
        [7, 8]])
tensor([[87, 88],
        [37, 30]])
tensor([[16, 21, 26],
        [30, 37, 44],
        [54, 59, 64]])


In [3]:
# 인덱싱 / 슬라이싱
data = torch.randn(4, 3)
print(data)
print(data[2, :]) # row vector
print(data[:, 1]) # column vector
print(data[2][1]) # matrix A의 (2, 1)의 값


tensor([[-1.1057,  0.2192,  1.7847],
        [ 0.0839,  1.5270, -1.0139],
        [-0.0279, -0.1419,  2.3965],
        [-0.0291,  0.2397, -1.3425]])
tensor([-0.0279, -0.1419,  2.3965])
tensor([ 0.2192,  1.5270, -0.1419,  0.2397])
tensor(-0.1419)


In [4]:
# 기본적인 통계 관련 함수 - 파이썬이도 있지만 torch 안에서는 torch 함수의 연산이 더 빠름
print(torch.sum(data))
print(torch.mean(data))
print(torch.var(data)) # 분산
print(torch.std(data)) # 표준편차
print()
# scalar value에 대해서 tensor 속의 값만 추출함. 풀어줌.
print(torch.sum(data).item())
print(torch.mean(data).item())
print(torch.var(data).item())
print(torch.std(data).item())

tensor(2.5900)
tensor(0.2158)
tensor(1.3535)
tensor(1.1634)

2.590029001235962
0.21583575010299683
1.353468656539917
1.1633867025375366


In [5]:
# Pytorch 조건문
print(torch.where(data > 0, torch.ones(data.shape), torch.zeros(data.shape)))

tensor([[0., 1., 1.],
        [1., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.]])
